/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AmgvsYXtirL
 */
import Link from "next/link";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";

export function FrontPage() {
  return (
    <div className="min-h-screen bg-black text-white p-10">
      <div className="max-w-4xl mx-auto">
        <aside className="fixed top-10 left-10">
          <nav className="space-y-4">
            <Link className="block text-lg font-bold text-white" href="#">
              home
            </Link>
            <Link className="block text-lg text-white" href="#">
              about
            </Link>
            <Link className="block text-lg text-white" href="#">
              blog
            </Link>
            <Link className="block text-lg text-white" href="#">
              guestbook
            </Link>
          </nav>
        </aside>
        <main className="mt-20">
          <h1 className="text-6xl font-bold">Tom Szpak</h1>
          <p className="mt-6 text-xl">
            Hey, I'm Tom. I'm a Software Developer with a focus on creating
            efficient and user-friendly applications.
          </p>
          <div className="mt-8 flex space-x-6">
            <Avatar>
              <AvatarImage
                alt="Tom Szpak"
                src="/placeholder.svg?height=128&width=128"
              />
              <AvatarFallback>TS</AvatarFallback>
            </Avatar>
            <div className="space-y-4">
              <p>
                <TwitterIcon className="inline mr-2" /> 3,200 tweets all time
              </p>
              <p>
                <GitForkIcon className="inline mr-2" /> 2,150 stars on this repo
              </p>
              <p>
                <ViewIcon className="inline mr-2" /> 750,000 blog views all time
              </p>
            </div>
          </div>
          <p className="mt-8 text-xl">
            I'm an active contributor to several open-source projects and have a
            strong passion for mentoring new developers. I've created
            educational content on modern web technologies and am continuously
            exploring the latest trends in software development.
          </p>
          <div className="mt-8 space-x-4">
            <Link className="block text-lg" href="#">
              follow me on twitter
            </Link>
            <Link className="block text-lg" href="#">
              get email updates
            </Link>
          </div>
        </main>
      </div>
    </div>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function GitForkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="18" r="3" />
      <circle cx="6" cy="6" r="3" />
      <circle cx="18" cy="6" r="3" />
      <path d="M18 9v1a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V9" />
      <path d="M12 12v3" />
    </svg>
  );
}

function ViewIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z" />
      <path d="M12 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
      <path d="M21 17v2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-2" />
      <path d="M21 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2" />
    </svg>
  );
}
